name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    uses: agentjido/github-actions/.github/workflows/elixir-lint.yml@main
    with:
      otp_version: "27.2.1"
      elixir_version: "1.18.2"
      lint_command: mix quality

  test:
    name: Test
    uses: agentjido/github-actions/.github/workflows/elixir-test.yml@main
    with:
      otp_versions: '["27.2.1"]'
      elixir_versions: '["1.18.2"]'
      test_command: mix test
      postgres: true
      postgres_image: pgvector/pgvector:pg16
